FROM ghcr.io/neomediatech/ubuntu-base:24.04

ENV SERVICE=sshd

LABEL org.opencontainers.image.service=${SERVICE} \
      org.label-schema.vcs-url=https://github.com/Neomediatech/${SERVICE}

RUN apt-get update && apt-get -y dist-upgrade && \
    apt-get install -y --no-install-recommends \
    vim bash-completion sudo curl wget xz-utils \
    rsyslog openssh-server openssl dnsutils telnet && \
    rm -f /etc/ssh/ssh_host_* && \
    rm -rf /var/lib/apt/lists* 

COPY bin/* /
RUN chmod +x /entrypoint.sh /cmd.sh

EXPOSE 22
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/tini", "--", "/cmd.sh"]
