FROM ghcr.io/neomediatech/ubuntu-base:20.04

ENV SERVICE=sshd

LABEL org.opencontainers.image.service=${SERVICE} \
      org.opencontainers.image.source=https://github.com/neomediatech/${SERVICE} \
      org.opencontainers.package.name=openssh-server

RUN apt-get update && apt-get -y dist-upgrade && \
    apt-get install -y --no-install-recommends \
    vim bash-completion sudo xz-utils \
    rsyslog openssh-server openssl dnsutils telnet && \
    rm -f /etc/ssh/ssh_host_* && \
    rm -rf /var/lib/apt/lists* 

COPY bin/* /
RUN chmod +x /entrypoint.sh /cmd.sh

EXPOSE 22
ENTRYPOINT ["/entrypoint.sh"]
CMD ["/tini", "--", "/cmd.sh"]
