name: Build and Scan Docker Image

on:
  push:
  #pull_request:
  workflow_dispatch: # Permette di avviare il workflow manualmente dalla UI di GitHub

jobs:
  build-and-scan:
    secrets: inherit
    strategy:
      matrix:
        type: []
        version: [latest, 24.04, 22.04, 20.04]
      max-parallel: 1
      # non posso parallellizzare il processo perché l'upload delle immagini va in errore con "permission denied"
    uses: Neomediatech/gh-workflows/.github/workflows/build-and-scan-docker-image.yml@main
    with:
      dockerfile: "Dockerfile.${{ matrix.version }}"
      dockerdir: "."
      #dockerdir: ${{ matrix.type }}
      dockertag: ${{ matrix.version }}
      #dockertag: ${{ matrix.version }}-${{ matrix.type }}

  push-report-to-repo:
    strategy:
      matrix:
        type: []
        version: [latest, 24.04, 22.04, 20.04]
      max-parallel: 1
    needs: [build-and-scan]
    secrets: inherit
    uses: Neomediatech/gh-workflows/.github/workflows/copy-file-to-another-repo.yml@main
    with:
      file_id: ${{ needs.build-and-scan.outputs.uploaded-file-id }}
      filename: ${{ needs.build-and-scan.outputs.file_to_copy_output }}
      dockertag: ${{ matrix.version }}
      #dockertag: ${{ matrix.version }}-${{ matrix.type }}

